FROM golang:buster AS go-build-env
WORKDIR /app

RUN apt-get update
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get install -y build-essential libwebkit2gtk-4.0-dev ca-certificates libglib2.0-dev
RUN curl -sSL https://get.docker.com | sh
