// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc/proto/models/kiosk.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumScreenAction int32

const (
	EnumScreenAction_START      EnumScreenAction = 0
	EnumScreenAction_UPDATE     EnumScreenAction = 1
	EnumScreenAction_STOP       EnumScreenAction = 2
	EnumScreenAction_POWEROFF   EnumScreenAction = 3
	EnumScreenAction_POWERON    EnumScreenAction = 4
	EnumScreenAction_SCREENSHOT EnumScreenAction = 5
)

var EnumScreenAction_name = map[int32]string{
	0: "START",
	1: "UPDATE",
	2: "STOP",
	3: "POWEROFF",
	4: "POWERON",
	5: "SCREENSHOT",
}

var EnumScreenAction_value = map[string]int32{
	"START":      0,
	"UPDATE":     1,
	"STOP":       2,
	"POWEROFF":   3,
	"POWERON":    4,
	"SCREENSHOT": 5,
}

func (x EnumScreenAction) String() string {
	return proto.EnumName(EnumScreenAction_name, int32(x))
}

func (EnumScreenAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_943e55fd7ffbcf07, []int{0}
}

type EnumScreenPowerState int32

const (
	EnumScreenPowerState_SCREENPOWERSTATEOFF EnumScreenPowerState = 0
	EnumScreenPowerState_SCREENPOWERSTATEON  EnumScreenPowerState = 1
)

var EnumScreenPowerState_name = map[int32]string{
	0: "SCREENPOWERSTATEOFF",
	1: "SCREENPOWERSTATEON",
}

var EnumScreenPowerState_value = map[string]int32{
	"SCREENPOWERSTATEOFF": 0,
	"SCREENPOWERSTATEON":  1,
}

func (x EnumScreenPowerState) String() string {
	return proto.EnumName(EnumScreenPowerState_name, int32(x))
}

func (EnumScreenPowerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_943e55fd7ffbcf07, []int{1}
}

type KioskRequest struct {
	Content              string           `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Title                string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SizeW                int64            `protobuf:"varint,3,opt,name=size_w,json=sizeW,proto3" json:"size_w,omitempty"`
	SizeH                int64            `protobuf:"varint,4,opt,name=size_h,json=sizeH,proto3" json:"size_h,omitempty"`
	Action               EnumScreenAction `protobuf:"varint,5,opt,name=action,proto3,enum=models.EnumScreenAction" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *KioskRequest) Reset()         { *m = KioskRequest{} }
func (m *KioskRequest) String() string { return proto.CompactTextString(m) }
func (*KioskRequest) ProtoMessage()    {}
func (*KioskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_943e55fd7ffbcf07, []int{0}
}

func (m *KioskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KioskRequest.Unmarshal(m, b)
}
func (m *KioskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KioskRequest.Marshal(b, m, deterministic)
}
func (m *KioskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KioskRequest.Merge(m, src)
}
func (m *KioskRequest) XXX_Size() int {
	return xxx_messageInfo_KioskRequest.Size(m)
}
func (m *KioskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KioskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KioskRequest proto.InternalMessageInfo

func (m *KioskRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *KioskRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *KioskRequest) GetSizeW() int64 {
	if m != nil {
		return m.SizeW
	}
	return 0
}

func (m *KioskRequest) GetSizeH() int64 {
	if m != nil {
		return m.SizeH
	}
	return 0
}

func (m *KioskRequest) GetAction() EnumScreenAction {
	if m != nil {
		return m.Action
	}
	return EnumScreenAction_START
}

type KioskRespose struct {
	Content              string               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SizeW                int64                `protobuf:"varint,3,opt,name=size_w,json=sizeW,proto3" json:"size_w,omitempty"`
	SizeH                int64                `protobuf:"varint,4,opt,name=size_h,json=sizeH,proto3" json:"size_h,omitempty"`
	Screenshot           []byte               `protobuf:"bytes,5,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
	PowerState           EnumScreenPowerState `protobuf:"varint,6,opt,name=power_state,json=powerState,proto3,enum=models.EnumScreenPowerState" json:"power_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *KioskRespose) Reset()         { *m = KioskRespose{} }
func (m *KioskRespose) String() string { return proto.CompactTextString(m) }
func (*KioskRespose) ProtoMessage()    {}
func (*KioskRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_943e55fd7ffbcf07, []int{1}
}

func (m *KioskRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KioskRespose.Unmarshal(m, b)
}
func (m *KioskRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KioskRespose.Marshal(b, m, deterministic)
}
func (m *KioskRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KioskRespose.Merge(m, src)
}
func (m *KioskRespose) XXX_Size() int {
	return xxx_messageInfo_KioskRespose.Size(m)
}
func (m *KioskRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_KioskRespose.DiscardUnknown(m)
}

var xxx_messageInfo_KioskRespose proto.InternalMessageInfo

func (m *KioskRespose) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *KioskRespose) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *KioskRespose) GetSizeW() int64 {
	if m != nil {
		return m.SizeW
	}
	return 0
}

func (m *KioskRespose) GetSizeH() int64 {
	if m != nil {
		return m.SizeH
	}
	return 0
}

func (m *KioskRespose) GetScreenshot() []byte {
	if m != nil {
		return m.Screenshot
	}
	return nil
}

func (m *KioskRespose) GetPowerState() EnumScreenPowerState {
	if m != nil {
		return m.PowerState
	}
	return EnumScreenPowerState_SCREENPOWERSTATEOFF
}

type KioskScreenshotRespose struct {
	Screenshot           []byte   `protobuf:"bytes,1,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KioskScreenshotRespose) Reset()         { *m = KioskScreenshotRespose{} }
func (m *KioskScreenshotRespose) String() string { return proto.CompactTextString(m) }
func (*KioskScreenshotRespose) ProtoMessage()    {}
func (*KioskScreenshotRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_943e55fd7ffbcf07, []int{2}
}

func (m *KioskScreenshotRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KioskScreenshotRespose.Unmarshal(m, b)
}
func (m *KioskScreenshotRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KioskScreenshotRespose.Marshal(b, m, deterministic)
}
func (m *KioskScreenshotRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KioskScreenshotRespose.Merge(m, src)
}
func (m *KioskScreenshotRespose) XXX_Size() int {
	return xxx_messageInfo_KioskScreenshotRespose.Size(m)
}
func (m *KioskScreenshotRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_KioskScreenshotRespose.DiscardUnknown(m)
}

var xxx_messageInfo_KioskScreenshotRespose proto.InternalMessageInfo

func (m *KioskScreenshotRespose) GetScreenshot() []byte {
	if m != nil {
		return m.Screenshot
	}
	return nil
}

func init() {
	proto.RegisterEnum("models.EnumScreenAction", EnumScreenAction_name, EnumScreenAction_value)
	proto.RegisterEnum("models.EnumScreenPowerState", EnumScreenPowerState_name, EnumScreenPowerState_value)
	proto.RegisterType((*KioskRequest)(nil), "models.KioskRequest")
	proto.RegisterType((*KioskRespose)(nil), "models.KioskRespose")
	proto.RegisterType((*KioskScreenshotRespose)(nil), "models.KioskScreenshotRespose")
}

func init() {
	proto.RegisterFile("pkg/grpc/proto/models/kiosk.proto", fileDescriptor_943e55fd7ffbcf07)
}

var fileDescriptor_943e55fd7ffbcf07 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xc1, 0xae, 0xd2, 0x40,
	0x14, 0x65, 0x80, 0x16, 0xb8, 0x10, 0x1c, 0x47, 0xc4, 0x59, 0x18, 0x83, 0xac, 0x08, 0x0b, 0x6a,
	0x74, 0xe3, 0xc6, 0x45, 0xd5, 0x22, 0x89, 0x09, 0x6d, 0x66, 0x6a, 0x48, 0x5c, 0x48, 0xb0, 0x4e,
	0xa0, 0x01, 0x3a, 0xb5, 0x33, 0x84, 0xc4, 0x8f, 0xf1, 0x87, 0xde, 0x4f, 0xbd, 0x74, 0xfa, 0x28,
	0xef, 0xc1, 0xdb, 0xbe, 0xdd, 0x9c, 0x73, 0xcf, 0xdc, 0x7b, 0xce, 0xcd, 0x85, 0xb7, 0xe9, 0x76,
	0xed, 0xac, 0xb3, 0x34, 0x72, 0xd2, 0x4c, 0x6a, 0xe9, 0xec, 0xe5, 0x1f, 0xb1, 0x53, 0xce, 0x36,
	0x96, 0x6a, 0x3b, 0x31, 0x14, 0xb1, 0x0b, 0x6e, 0xf8, 0x1f, 0x41, 0xe7, 0x7b, 0xce, 0x33, 0xf1,
	0xf7, 0x20, 0x94, 0x26, 0x14, 0x1a, 0x91, 0x4c, 0xb4, 0x48, 0x34, 0x45, 0x03, 0x34, 0x6a, 0xb1,
	0x13, 0x24, 0x3d, 0xb0, 0x74, 0xac, 0x77, 0x82, 0x56, 0x0d, 0x5f, 0x00, 0xf2, 0x12, 0x6c, 0x15,
	0xff, 0x13, 0xcb, 0x23, 0xad, 0x0d, 0xd0, 0xa8, 0xc6, 0xac, 0x1c, 0x2d, 0x4a, 0x7a, 0x43, 0xeb,
	0x67, 0x7a, 0x46, 0xde, 0x81, 0xbd, 0x8a, 0x74, 0x2c, 0x13, 0x6a, 0x0d, 0xd0, 0xa8, 0xfb, 0x9e,
	0x4e, 0x0a, 0x1f, 0x13, 0x2f, 0x39, 0xec, 0x79, 0x94, 0x09, 0x91, 0xb8, 0xa6, 0xce, 0xee, 0x74,
	0xc3, 0x9b, 0xb3, 0x41, 0x95, 0x4a, 0x25, 0x9e, 0xd8, 0xe0, 0x1b, 0x00, 0x65, 0x6c, 0xa8, 0x8d,
	0xd4, 0xc6, 0x64, 0x87, 0xdd, 0x63, 0xc8, 0x27, 0x68, 0xa7, 0xf2, 0x28, 0xb2, 0xa5, 0xd2, 0x2b,
	0x2d, 0xa8, 0x6d, 0x52, 0xbc, 0xbe, 0x4e, 0x11, 0xe4, 0x22, 0x9e, 0x6b, 0x18, 0xa4, 0xe5, 0x7b,
	0xf8, 0x11, 0xfa, 0x26, 0x0c, 0x2f, 0x3b, 0x9e, 0x62, 0x3d, 0x1c, 0x8c, 0x2e, 0x07, 0x8f, 0x7f,
	0x01, 0xbe, 0xdc, 0x11, 0x69, 0x81, 0xc5, 0x43, 0x97, 0x85, 0xb8, 0x42, 0x00, 0xec, 0x1f, 0xc1,
	0x57, 0x37, 0xf4, 0x30, 0x22, 0x4d, 0xa8, 0xf3, 0xd0, 0x0f, 0x70, 0x95, 0x74, 0xa0, 0x19, 0xf8,
	0x0b, 0x8f, 0xf9, 0xd3, 0x29, 0xae, 0x91, 0x36, 0x34, 0x0a, 0x34, 0xc7, 0x75, 0xd2, 0x05, 0xe0,
	0x5f, 0x98, 0xe7, 0xcd, 0xf9, 0xcc, 0x0f, 0xb1, 0x35, 0xfe, 0x06, 0xbd, 0xc7, 0xdc, 0x93, 0x57,
	0xf0, 0xa2, 0xd0, 0x99, 0xaf, 0x3c, 0x74, 0x43, 0x2f, 0xef, 0x56, 0x21, 0x7d, 0x20, 0x57, 0x85,
	0x39, 0x46, 0x9f, 0x9f, 0xff, 0x7c, 0x56, 0x9e, 0x5f, 0xb1, 0x96, 0xdf, 0xb6, 0xb9, 0xb9, 0x0f,
	0xb7, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x44, 0xc6, 0x95, 0x98, 0x02, 0x00, 0x00,
}
