// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc/proto/models/kiosk.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumState int32

const (
	EnumState_RUNNING EnumState = 0
	EnumState_STOPPED EnumState = 1
	EnumState_UNKNOWN EnumState = 2
)

var EnumState_name = map[int32]string{
	0: "RUNNING",
	1: "STOPPED",
	2: "UNKNOWN",
}

var EnumState_value = map[string]int32{
	"RUNNING": 0,
	"STOPPED": 1,
	"UNKNOWN": 2,
}

func (x EnumState) String() string {
	return proto.EnumName(EnumState_name, int32(x))
}

func (EnumState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_943e55fd7ffbcf07, []int{0}
}

type KioskState struct {
	Content              string    `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Title                string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SizeW                int64     `protobuf:"varint,3,opt,name=size_w,json=sizeW,proto3" json:"size_w,omitempty"`
	SizeH                int64     `protobuf:"varint,4,opt,name=size_h,json=sizeH,proto3" json:"size_h,omitempty"`
	State                EnumState `protobuf:"varint,5,opt,name=state,proto3,enum=models.EnumState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *KioskState) Reset()         { *m = KioskState{} }
func (m *KioskState) String() string { return proto.CompactTextString(m) }
func (*KioskState) ProtoMessage()    {}
func (*KioskState) Descriptor() ([]byte, []int) {
	return fileDescriptor_943e55fd7ffbcf07, []int{0}
}

func (m *KioskState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KioskState.Unmarshal(m, b)
}
func (m *KioskState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KioskState.Marshal(b, m, deterministic)
}
func (m *KioskState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KioskState.Merge(m, src)
}
func (m *KioskState) XXX_Size() int {
	return xxx_messageInfo_KioskState.Size(m)
}
func (m *KioskState) XXX_DiscardUnknown() {
	xxx_messageInfo_KioskState.DiscardUnknown(m)
}

var xxx_messageInfo_KioskState proto.InternalMessageInfo

func (m *KioskState) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *KioskState) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *KioskState) GetSizeW() int64 {
	if m != nil {
		return m.SizeW
	}
	return 0
}

func (m *KioskState) GetSizeH() int64 {
	if m != nil {
		return m.SizeH
	}
	return 0
}

func (m *KioskState) GetState() EnumState {
	if m != nil {
		return m.State
	}
	return EnumState_RUNNING
}

func init() {
	proto.RegisterEnum("models.EnumState", EnumState_name, EnumState_value)
	proto.RegisterType((*KioskState)(nil), "models.KioskState")
}

func init() {
	proto.RegisterFile("pkg/grpc/proto/models/kiosk.proto", fileDescriptor_943e55fd7ffbcf07)
}

var fileDescriptor_943e55fd7ffbcf07 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0xc8, 0x4e, 0xd7,
	0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0xcd, 0x4f, 0x49, 0xcd,
	0x29, 0xd6, 0xcf, 0xce, 0xcc, 0x2f, 0xce, 0xd6, 0x03, 0x0b, 0x09, 0xb1, 0x41, 0xc4, 0x94, 0x26,
	0x33, 0x72, 0x71, 0x79, 0x83, 0xc4, 0x83, 0x4b, 0x12, 0x4b, 0x52, 0x85, 0x24, 0xb8, 0xd8, 0x93,
	0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21,
	0x11, 0x2e, 0xd6, 0x92, 0xcc, 0x92, 0x9c, 0x54, 0x09, 0x26, 0xb0, 0x38, 0x84, 0x23, 0x24, 0xca,
	0xc5, 0x56, 0x9c, 0x59, 0x95, 0x1a, 0x5f, 0x2e, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x0a,
	0xe2, 0x85, 0xc3, 0x85, 0x33, 0x24, 0x58, 0x10, 0xc2, 0x1e, 0x42, 0xea, 0x5c, 0xac, 0xc5, 0x20,
	0x6b, 0x24, 0x58, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x04, 0xf5, 0x20, 0x8e, 0xd0, 0x73, 0xcd, 0x2b,
	0xcd, 0x05, 0xdb, 0x1f, 0x04, 0x91, 0xd7, 0x32, 0xe2, 0xe2, 0x84, 0x8b, 0x09, 0x71, 0x73, 0xb1,
	0x07, 0x85, 0xfa, 0xf9, 0x79, 0xfa, 0xb9, 0x0b, 0x30, 0x80, 0x38, 0xc1, 0x21, 0xfe, 0x01, 0x01,
	0xae, 0x2e, 0x02, 0x8c, 0x20, 0x4e, 0xa8, 0x9f, 0xb7, 0x9f, 0x7f, 0xb8, 0x9f, 0x00, 0x93, 0x93,
	0x60, 0x14, 0x3f, 0xdc, 0xdb, 0x10, 0x73, 0x93, 0xd8, 0xc0, 0x7e, 0x35, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x3c, 0xec, 0xf6, 0x01, 0x10, 0x01, 0x00, 0x00,
}
